blank_issues_enabled: false

contact_links:
  - name: ❓ Ask a Question / General Discussion
    url: https://discord.gg/pMBdw4q5bV
    about: Please ask questions and discuss ideas on our Discord server.